import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const tasks = sqliteTable("tasks", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  project: text("project").notNull(),
  owner: text("owner").notNull(),
  assignee: text("assignee").notNull(),
  assigneeEmail: text("assignee_email").notNull().default(""),
  due: text("due").notNull(),
  priority: text("priority").notNull(),
  status: text("status").notNull(),
  description: text("description").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  taskType: text("task_type").notNull().default("General"),
  taskGroup: text("task_group").notNull().default("Store Tasks"),
});
export const comments = sqliteTable("comments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  taskId: integer("task_id").notNull(),
  body: text("body").notNull(),
  author: text("author").notNull(),
  createdAt: text("created_at").notNull(),
});
export const attachments = sqliteTable("attachments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  taskId: integer("task_id").notNull(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  size: integer("size").notNull(),
  objectKey: text("object_key").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: text("created_at").notNull(),
});
export const workspaces = sqliteTable("workspaces", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  region: text("region").notNull().default("Unassigned"),
  manager: text("manager").notNull().default(""),
  active: integer("active").notNull().default(1),
  createdAt: text("created_at").notNull(),
});
export const wholesaleOpportunities = sqliteTable("wholesale_opportunities", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  customerName: text("customer_name").notNull(),
  contactPerson: text("contact_person").notNull().default(""),
  contact: text("contact").notNull().default(""),
  email: text("email").notNull().default(""),
  customerType: text("customer_type").notNull().default("Independent Hardware"),
  province: text("province").notNull().default("Gauteng"),
  region: text("region").notNull().default(""),
  zone: text("zone").notNull().default(""),
  quotationNo: text("quotation_no").notNull().default(""),
  orderNo: text("order_no").notNull().default(""),
  value: real("value").notNull().default(0),
  gpPercent: real("gp_percent").notNull().default(0),
  stage: text("stage").notNull().default("Lead"),
  assignedTo: text("assigned_to").notNull().default(""),
  coordinator: text("coordinator").notNull().default(""),
  monthlyTarget: real("monthly_target").notNull().default(0),
  lastVisit: text("last_visit").notNull().default(""),
  nextFollowUp: text("next_follow_up").notNull().default(""),
  nextAction: text("next_action").notNull().default(""),
  customerNumber: text("customer_number").notNull().default(""),
  applicationStatus: text("application_status").notNull().default("Pending approval"),
  registeredName: text("registered_name").notNull().default(""),
  registrationNumber: text("registration_number").notNull().default(""),
  vatNumber: text("vat_number").notNull().default(""),
  natureOfBusiness: text("nature_of_business").notNull().default(""),
  yearsInBusiness: integer("years_in_business").notNull().default(0),
  branchCount: integer("branch_count").notNull().default(1),
  headOfficeAddress: text("head_office_address").notNull().default(""),
  postalCode: text("postal_code").notNull().default(""),
  website: text("website").notNull().default(""),
  legalEntity: text("legal_entity").notNull().default(""),
  owner1Name: text("owner1_name").notNull().default(""),
  owner1Id: text("owner1_id").notNull().default(""),
  owner1Position: text("owner1_position").notNull().default(""),
  owner1Mobile: text("owner1_mobile").notNull().default(""),
  owner2Name: text("owner2_name").notNull().default(""),
  owner2Id: text("owner2_id").notNull().default(""),
  owner2Position: text("owner2_position").notNull().default(""),
  owner2Mobile: text("owner2_mobile").notNull().default(""),
  purchasingContactName: text("purchasing_contact_name").notNull().default(""),
  purchasingContactMobile: text("purchasing_contact_mobile").notNull().default(""),
  purchasingContactEmail: text("purchasing_contact_email").notNull().default(""),
  accountsContactName: text("accounts_contact_name").notNull().default(""),
  accountsContactMobile: text("accounts_contact_mobile").notNull().default(""),
  accountsContactEmail: text("accounts_contact_email").notNull().default(""),
  deliveryAddress: text("delivery_address").notNull().default(""),
  deliveryContact: text("delivery_contact").notNull().default(""),
  deliveryContactMobile: text("delivery_contact_mobile").notNull().default(""),
  receivingHours: text("receiving_hours").notNull().default(""),
  deliveryRequirements: text("delivery_requirements").notNull().default(""),
  productCategories: text("product_categories").notNull().default("[]"),
  averageMonthlySpend: real("average_monthly_spend").notNull().default(0),
  orderingMethod: text("ordering_method").notNull().default(""),
  orderingFrequency: text("ordering_frequency").notNull().default(""),
  paymentTerms: text("payment_terms").notNull().default("COD / EFT Before Dispatch"),
  creditRequested: integer("credit_requested").notNull().default(0),
  priceGroup: text("price_group").notNull().default("Standard Wholesale"),
  declarationAccepted: integer("declaration_accepted").notNull().default(0),
  applicationSubmittedAt: text("application_submitted_at").notNull().default(""),
  approvedBy: text("approved_by").notNull().default(""),
  approvedAt: text("approved_at").notNull().default(""),
  approvalComments: text("approval_comments").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

export const wholesaleCustomerDocuments = sqliteTable("wholesale_customer_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  opportunityId: integer("opportunity_id").notNull(),
  documentType: text("document_type").notNull().default("Supporting document"),
  name: text("name").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  objectKey: text("object_key").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: text("created_at").notNull(),
});

export const wholesaleVisits = sqliteTable("wholesale_visits", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  opportunityId: integer("opportunity_id").notNull(),
  visitDate: text("visit_date").notNull(),
  visitType: text("visit_type").notNull().default("In person"),
  updateType: text("update_type").notNull().default("General follow-up"),
  contactPerson: text("contact_person").notNull().default(""),
  outcome: text("outcome").notNull().default(""),
  notes: text("notes").notNull().default(""),
  nextFollowUp: text("next_follow_up").notNull().default(""),
  scheduledTime: text("scheduled_time").notNull().default(""),
  purpose: text("purpose").notNull().default(""),
  visitStatus: text("visit_status").notNull().default("Completed"),
  area: text("area").notNull().default(""),
  visitAddress: text("visit_address").notNull().default(""),
  createdBy: text("created_by").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

export const wholesaleCustomerSequence = sqliteTable("wholesale_customer_sequence", {
  id: integer("id").primaryKey(),
  nextNumber: integer("next_number").notNull().default(1),
});
export const financialEntries = sqliteTable("financial_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  workspace: text("workspace").notNull(),
  entryType: text("entry_type").notNull(),
  category: text("category").notNull(),
  amount: real("amount").notNull().default(0),
  period: text("period").notNull(),
  description: text("description").notNull().default(""),
  expenseNature: text("expense_nature").notNull().default("Variable"),
  recurring: integer("recurring").notNull().default(0),
  effectiveTo: text("effective_to").notNull().default(""),
  createdAt: text("created_at").notNull(),
});
export const commissionSettings = sqliteTable("commission_settings", {
  id: integer("id").primaryKey(),
  baseTarget: real("base_target").notNull().default(1000000),
  baseGpThreshold: real("base_gp_threshold").notNull().default(10),
  acceleratorGpThreshold: real("accelerator_gp_threshold")
    .notNull()
    .default(15),
  repBaseRate: real("rep_base_rate").notNull().default(5),
  repAcceleratorRate: real("rep_accelerator_rate").notNull().default(6),
  coordinatorRate: real("coordinator_rate").notNull().default(2),
  headRate: real("head_rate").notNull().default(2),
  updatedAt: text("updated_at").notNull(),
});
export const sopDocuments = sqliteTable("sop_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  documentType: text("document_type").notNull().default("SOP"),
  department: text("department").notNull().default("Operations"),
  workspace: text("workspace").notNull().default("Head Office"),
  owner: text("owner").notNull().default("Operations"),
  reviewDate: text("review_date").notNull().default(""),
  notes: text("notes").notNull().default(""),
  fileName: text("file_name").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  objectKey: text("object_key").notNull(),
  status: text("status").notNull().default("Uploaded"),
  aiSummary: text("ai_summary").notNull().default(""),
  workflowJson: text("workflow_json").notNull().default("[]"),
  checklistJson: text("checklist_json").notNull().default("[]"),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const sopResources = sqliteTable("sop_resources", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sopId: integer("sop_id").notNull(),
  label: text("label").notNull(),
  resourceType: text("resource_type").notNull().default("Form / Checklist"),
  fileName: text("file_name").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  objectKey: text("object_key").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: text("created_at").notNull(),
});

export const sopTrainingRecords = sqliteTable(
  "sop_training_records",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    sopId: integer("sop_id").notNull(),
    memberEmail: text("member_email").notNull(),
    memberName: text("member_name").notNull(),
    status: text("status").notNull().default("Assigned"),
    signatureName: text("signature_name").notNull().default(""),
    readAt: text("read_at").notNull().default(""),
    trainedAt: text("trained_at").notNull().default(""),
    competencyStatus: text("competency_status").notNull().default("Pending"),
    assessedBy: text("assessed_by").notNull().default(""),
    notes: text("notes").notNull().default(""),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (table) => [
    uniqueIndex("sop_training_sop_member_unique").on(
      table.sopId,
      table.memberEmail,
    ),
  ],
);

export const teamMembers = sqliteTable("team_members", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  role: text("role").notNull().default("Member"),
  department: text("department").notNull().default("Operations"),
  active: integer("active").notNull().default(1),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  inviteStatus: text("invite_status").notNull().default("Active"),
  inviteToken: text("invite_token").notNull().default(""),
  inviteSentAt: text("invite_sent_at").notNull().default(""),
  acceptedAt: text("accepted_at").notNull().default(""),
  accessScope: text("access_scope").notNull().default("Assigned workspace"),
  workspaceAccess: text("workspace_access").notNull().default("[]"),
});

export const notifications = sqliteTable("notifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  recipientEmail: text("recipient_email").notNull(),
  taskId: integer("task_id").notNull(),
  title: text("title").notNull(),
  message: text("message").notNull(),
  notificationType: text("notification_type").notNull().default("Assignment"),
  readAt: text("read_at").notNull().default(""),
  createdAt: text("created_at").notNull(),
});

export const developmentProjects = sqliteTable("development_projects", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  projectName: text("project_name").notNull(),
  siteLocation: text("site_location").notNull().default(""),
  projectType: text("project_type").notNull().default("New Store"),
  status: text("status").notNull().default("Planning"),
  ragStatus: text("rag_status").notNull().default("Green"),
  projectManager: text("project_manager").notNull().default(""),
  startDate: text("start_date").notNull().default(""),
  plannedOpeningDate: text("planned_opening_date").notNull().default(""),
  actualOpeningDate: text("actual_opening_date").notNull().default(""),
  approvedBudget: real("approved_budget").notNull().default(0),
  contingencyBudget: real("contingency_budget").notNull().default(0),
  stockBudget: real("stock_budget").notNull().default(0),
  progressPercent: integer("progress_percent").notNull().default(0),
  approvalStatus: text("approval_status").notNull().default("Pending approval"),
  approvedBy: text("approved_by").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const developmentExpenses = sqliteTable("development_expenses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  projectId: integer("project_id").notNull(),
  category: text("category").notNull(),
  supplierContractor: text("supplier_contractor").notNull().default(""),
  description: text("description").notNull().default(""),
  budgetedAmount: real("budgeted_amount").notNull().default(0),
  committedAmount: real("committed_amount").notNull().default(0),
  actualAmount: real("actual_amount").notNull().default(0),
  paidAmount: real("paid_amount").notNull().default(0),
  expenseStatus: text("expense_status").notNull().default("Budgeted"),
  invoiceNumber: text("invoice_number").notNull().default(""),
  expenseDate: text("expense_date").notNull().default(""),
  dueDate: text("due_date").notNull().default(""),
  owner: text("owner").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdBy: text("created_by").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const developmentDocuments = sqliteTable("development_documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  projectId: integer("project_id").notNull(),
  expenseId: integer("expense_id").notNull().default(0),
  documentType: text("document_type").notNull().default("Invoice / Quotation"),
  name: text("name").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  objectKey: text("object_key").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: text("created_at").notNull(),
});
